config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: 'buoys#index'
  get '/design', to: 'pages#design'
  get '/pages/home', to: 'pages#home'
  get '/mybuoys', to: 'buoys#mybuoys'

  resources :buoys, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index ] do
    resources :reviews, only: [:new, :create]
  end

  put 'bookings/:id/confirm', to: 'bookings#confirm', as: 'confirm_booking'
  put 'bookings/:id/reject', to: 'bookings#reject', as: 'reject_booking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :buoy
  has_one :review
  validates :start_date, :end_date, :status, presence: true
end

app/models/buoy.rb
class Buoy < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_name_description_and_address,
    against: [ :name, :description, :address ],
    using: {
      tsearch: { prefix: true }
    }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
  SIZE = %w[ XS S M L XL XXL ]
  CATEGORY = %i[ funny luxury fashionable cute safety ridiculous boat ]
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  validates :name, :photo, :category, :price, :size, :description, :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :buoys
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:confirm, :reject]

  def index
    @bookings = policy_scope(Booking)
    @bookings_owner = BookingPolicy::Scope.new(current_user, Booking).owner
  end

  def new
    @booking = Booking.new
  end

  def create
    @buoy = Buoy.find(params[:buoy_id])
    @booking = Booking.new(booking_params)
    @booking.start_date = start_date
    @booking.end_date = end_date
    @booking.user = current_user
    @booking.buoy = @buoy
    @reviews = Review.all
    if @booking.save
      redirect_to bookings_path
    else
      render 'buoys/show'
    end
    authorize @booking
  end

  def confirm
    @booking.status = 'Confirmed'
    authorize @booking
    @booking.save
    @bookings_owner = BookingPolicy::Scope.new(current_user, Booking).owner
  end

  def reject
    @booking.status = 'Rejected'
    authorize @booking
    @booking.save
    @bookings_owner = BookingPolicy::Scope.new(current_user, Booking).owner
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date, :date_range)
  end

  def start_date
    date = params["booking"]["start_date"].split(' to ')
    return nil if date[0].nil?

    date[0].to_date
  end

  def end_date
    date = params["booking"]["start_date"].split(' to ')
    return nil if date[1].nil?

    date[1].to_date
  end
end

app/controllers/buoys_controller.rb
class BuoysController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_buoy, only: [:show, :edit, :update, :destroy]
  before_action :set_booking, only: [:show]

  def index
    @buoys = policy_scope(Buoy).where.not(latitude: nil, longitude: nil)

    if params[:query].present?
      @buoys = Buoy.search_by_name_description_and_address("%#{params[:query]}%")
    else
      @buoys
    end

    @markers = @buoys.map do |buoy|
      {
        lat: buoy.latitude,
        lng: buoy.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { buoy: buoy }),
        image_url: helpers.asset_url('inflatable.svg')
      }
    end
  end

  def new
    @buoy = Buoy.new
    authorize @buoy
  end

  def create
    @buoy = Buoy.new(buoy_params)
    @buoy.user = current_user
    if @buoy.valid?
      @buoy.save
      redirect_to buoys_path
    else
      render :new
    end
    authorize @buoy
  end

  def show
    authorize @buoy
    @reviews = @buoy.reviews
    @marker = [
      {
        lat: @buoy.latitude,
        lng: @buoy.longitude,
        image_url: helpers.asset_url('inflatable.svg')
      }
    ]
  end

  def update
    authorize @buoy
    @buoy.update(buoy_params)
    redirect_to mybuoys_path
  end

  def edit
    authorize @buoy
  end

  def destroy
    authorize @buoy
    @buoy.destroy
    redirect_to mybuoys_path
  end

  def mybuoys
    authorize :buoy, :mybuoys?
    @mybuoys = current_user.buoys
  end

  private

  def buoy_params
    params.require(:buoy).permit(:name, :photo, :category, :price, :size, :address, :color, :description, :user_id)
  end

  def set_buoy
    @buoy = Buoy.find(params[:id])
  end

  def set_booking
    @booking = Booking.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :design]

  def home
  end

  def design
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_current_booking

  def new
    @review = Review.new
    @buoy = @booking.buoy
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to buoy_path(@booking.buoy)
    else
      flash[:alert] = "Please fill the review carefully :)"
      render :new
    end
    authorize @review
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_current_booking
    @booking = Booking.find(params[:booking_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_table_bookings.html.erb
<table width=100% id="table-request">
  <tr class="text-center">
    <th>Buoy name</th>
    <th>Photo</th>
    <th>Status</th>
    <th>From</th>
    <th>To</th>
    <th>Price</th>
  </tr>
  <% bookings_owner.select{ |booking| booking.status == "Pending" }.each do |booking| %>
    <tr class="text-center" id="request-<%= booking.id %>">
      <td><%= booking.buoy.name %></td>
      <td><%= cl_image_tag booking.buoy.photo, width: 50, height: 50, crop: :thumb, radius: 'max', gravity: 'auto' %></td>
      <td><%= booking.status %></td>
      <td><%= booking.start_date %></td>
      <td><%= booking.end_date %></td>
      <td><%= (booking.end_date - booking.start_date).to_i * booking.buoy.price %>,00 €</td>
      <td>
        <div class="d-flex justify-content-center">
          <%= link_to "Confirm" , confirm_booking_path(booking), method: :put, remote: true, class: "btn btn-success margin-btn btn-radius", id:"confirm" %>
          <%= link_to "Reject" , reject_booking_path(booking), method: :put, remote: true, class: "btn btn-danger btn-radius", id:"reject" %>
        </div>
      </td>
      </div> 
    </tr> 
  <% end %>
  <% bookings_owner.reject{ |booking| booking.status == "Pending" }.each do |booking| %>
    <tr class="text-center text-secondary table-grey" id="request-<%= booking.id %>">
      <td><%= booking.buoy.name %></td>
      <td><%= cl_image_tag booking.buoy.photo, width: 50, height: 50, crop: :thumb, radius: 'max', gravity: 'auto' %></td>
      <td><%= booking.status %></td>
      <td><%= booking.start_date %></td>
      <td><%= booking.end_date %></td>
      <td><%= (booking.end_date - booking.start_date).to_i * booking.buoy.price %>,00 €</td>
      <% if booking.status == "Confirmed" %>
        <td> <i class="fas fa-check"></i> <%= booking.status %></td>  
      <% else %>
        <td> <i class="fas fa-times"></i> <%= booking.status %></td>
      <% end %>
      </div> 
    </tr> 
  <% end %>  
</table>

app/views/bookings/confirm.js.erb
  var bookingTable = document.getElementById("table-request");
  bookingTable.innerHTML = '<%= j render 'bookings/table_bookings', bookings_owner: @bookings_owner %>'

app/views/bookings/index.html.erb
<div class="container">

  <div class="nav row nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <a class="col-12 col-md-6 nav-link active" id="v-pills-request-tab" data-toggle="pill" href="#v-pills-request" role="tab" aria-controls="v-pills-request" aria-selected="true">My bookings</a>
    <a class="col-12 col-md-6 nav-link" id="v-pills-booking-tab" data-toggle="pill" href="#v-pills-booking" role="tab" aria-controls="v-pills-booking" aria-selected="false">My pending requests</a>
  </div>

  <div class="tab-content" id="v-pills-tabContent">
    <div class="tab-pane fade" id="v-pills-booking" role="tabpanel" aria-labelledby="v-pills-booking-tab">
      
      <div class="text-center mt-5 mb-2" style="width: 100%;">
        <h2>You have pending requests to confirm, or not...</h2>
      </div>

      <div class="card-booking">
        <% pendings = @bookings.map do |booking| %>
          <% booking.status == "Pending" %>
        <% end %>
        <% if pendings.include?(true) %>
          <%= render 'table_bookings', bookings_owner: @bookings_owner %>
        <% else %>
          <div class="text-center w-100">
            <p><i>Oops, you don't have any request for the moment...</i></p>
            <p><i>Don't hesitate to add more buoys!</i></p>
            <%= link_to "Add a&nbsp;&nbsp;<i class='far fa-life-ring'></i>".html_safe, new_buoy_path, class: "btn btn-success btn-radius" %>
          </div>
        <% end %>

      </div>
    </div>

    <div class="tab-pane fade show active" id="v-pills-request" role="tabpanel" aria-labelledby="v-pills-request-tab">
    
      <div class="text-center mt-5 mb-2" style="width: 100%;">
        <h2> Your own reservations:</h2>
      </div>
      <div class="card-booking">
        <% if @bookings.empty? %>
          <div class="text-center w-100">
            <p><i>Oops, you don't have any reservation for the moment...</i></p>
            <p><i>Don't hesitate to take a look at our buoys!</i></p>
            <%= link_to "See all &nbsp;&nbsp;<i class='far fa-life-ring'></i>".html_safe, buoys_path, class: "btn btn-success btn-radius" %>
          </div>
        <% else %>
          <table width=100%>
            <tr class="text-center">
              <th>Buoy name</th>
              <th>Photo</th>
              <th>Status</th>
              <th>From</th>
              <th>To</th>
              <th>Price</th>
            </tr>
              <% @bookings.each do |booking| %>
                <tr class="text-center">
                  <td><%= booking.buoy.name %></td>
                  <td><%= cl_image_tag booking.buoy.photo, width: 50, height: 50, crop: :thumb, radius: 'max', gravity: 'auto' %></td>
                  <td><%= booking.status %></td>
                  <td><%= booking.start_date %></td>
                  <td><%= booking.end_date %></td>
                  <td><%= (booking.end_date - booking.start_date).to_i * booking.buoy.price %>,00 €</td>
                  <% if booking.end_date < Date.today %>
                    <td>
                    <%= link_to "Rate", new_booking_review_path(booking), { class: "btn btn-success btn-radius"} %>
                    </td>
                  <% end %>
                </tr> 
              <% end %>
          </table>
        <% end %>
      </div>

    </div>

  </div>

</div>

app/views/bookings/reject.js.erb
var bookingTable = document.getElementById("table-request");
  bookingTable.innerHTML = '<%= j render 'bookings/table_bookings', bookings_owner: @bookings_owner %>'

app/views/buoys/_infowindow.html.erb
<div class="popup">
  <%= link_to buoy_path(buoy) do %>
    <%= cl_image_tag(buoy.photo, width: 180, :radius=>"10", gravity: "auto", crop: :fill) %>
    <div class="popup-description">
      <h3><%= buoy.name  %></h3>
      <h5><%= buoy.address  %></h5>
      <div class="d-flex justify-content-around">
        <p><i class="fas fa-paperclip"></i>  <%= buoy.category %></p>
        <p><i class="fas fa-ruler-combined">  </i><%= buoy.size  %></p>
        <p><i class="fas fa-tag"></i>  <%= buoy.price %>€</p>
      </div>
      <p>
        <%= buoy.description %>
      </p>
    </div>
  <% end %>
</div>

app/views/buoys/edit.html.erb
<div class="container">
  <div class="form-container-large">
    <h2 class="caption p-3">Modify your buoy right here :  </h2>
    <%= simple_form_for @buoy do |f| %>
      <%= f.input :name %>
      <%= f.input :color %>
      <%= f.input :size, collection: Buoy::SIZE %>
      <%= f.input :category, collection: Buoy::CATEGORY %>
      <div class="update-image">
        <%= cl_image_tag @buoy.photo %>
        <%= f.input :photo %>
      </div>
        <%= f.input :price %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Update a buoy !", class: "btn btn-success" %>
      <% end %>
  </div>
</div>

app/views/buoys/index.html.erb
<body style="background-color: white;">

  <div class="home-banner">
    <div>
      <h2>Bored at the pool ? Don't forget the most important tool!</h2>
      <h1>Book a Buoy! </h1>

      <div class="search-form row justify-content-center">
        <div class="col-9 pr-0">
          <%= form_tag buoys_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control input-search",
              placeholder: "Find your buoy"
            %>
        </div>
        <div class="col-3 pl-0 text-left">
          <%= submit_tag 'Search', class: "form-submit btn btn-search" %>
          <% end %>
        </div>
      </div>



    </div>
  </div>

  <div class="container pt-4">
    <h2 class="caption text-center"> Find the perfect buoy next door...</h2>
      <div class="row">
        <% @buoys.each do |buoy| %>
          <div class="col-12 col-lg-4 col-md-6 col-sm-12">
            <div class="card-product" style="background-image: url('<%= cl_image_path buoy.photo, height: 300, width: 400, crop: :fill %>')">
              <% if buoy.user == current_user %>
                <div id="owner-tag">
                    <i class="fas fa-crown"></i> Me
                </div>
              <% end %>
              <div class="card-product-description">
                <h3><%= buoy.name %></h3>
                <h5><%= truncate(buoy.description, length: 30) %></h5>
                <div class="d-flex justify-content-around">
                  <p><i class="fas fa-paperclip"></i><%= buoy.category %></p>
                  <p><i class="fas fa-ruler-combined"></i><%= buoy.size %></p>
                  <p><i class="fas fa-tag"></i><%= buoy.price %>€</p>
                </div>
                <p>
                  <%= buoy.address.split(',')[1] %>
                </p>
                  <%= link_to buoy_path(buoy) do %>
                  <button class="btn-book btn btn-success btn-radius">Choose me</button>
                  <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

  <h2 class="caption text-center">... or all around the world!</h2>
    <div class="main-map mt-5">
      <div
        id="map"
        style="width: 100%;
        height: 400px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</body>

app/views/buoys/mybuoys.html.erb
<html>
  <head>
    <title> All of my buoys! </title>
    <meta name="description" content=" Checking out all of my buoys!">
    <meta charset="utf-8">
  </head>
  <body>
    <div class="container pt-6">
      <div class="row">
        <% @mybuoys.each do |buoy| %>
          <div class="col-12 col-lg-4 col-md-6 col-sm-12">
            <div class="card-product" style="background-image: url('<%= cl_image_path buoy.photo, height: 300, width: 400, crop: :fill %>')">
              <div class="card-product-description">
                <h3><%= buoy.name %></h3>
                <h5><%= truncate(buoy.description, length: 30) %></h5>
                <div class="d-flex justify-content-around">
                  <p><i class="fas fa-paperclip"></i><%= buoy.category %></p>
                  <p><i class="fas fa-ruler-combined"></i><%= buoy.size %></p>
                  <p><i class="fas fa-tag"></i><%= buoy.price %>€</p>
                </div>
                <p>
                  <%= buoy.address.split(',')[1] %>
                </p>
                <div class = "d-flex justify-content-around">
                  <%= link_to edit_buoy_path(buoy) do %>
                    <button class="btn-book btn btn-success btn-radius">Update</button>
                  <% end %>
                  <% if buoy.bookings.empty? %>
                    <%= link_to buoy_path(buoy), method: :delete, :data => {:confirm => 'Are you sure?'} do %>
                      <button class="btn-book btn btn-danger btn-radius">Delete</button>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/buoys/new.html.erb
<div class="container">
  <div class="form-container-large">
    <h2 class="caption p-3">Please add all infos regarding the new buoy:  </h2>
      <%= simple_form_for @buoy do |f| %>
        <%= f.input :name %>
        <%= f.input :color %>
        <%= f.input :size, collection: Buoy::SIZE %>
        <%= f.input :category, collection: Buoy::CATEGORY %>
        <%= f.input :photo %>
        <%= f.input :price %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Let your buoy be booked!", class: "btn btn-success" %>
      <% end %>
  </div>
</div>

app/views/buoys/show.html.erb
<div class="container">
  <h2 class="caption p-3">All you need to know about this buoy, <%= @buoy.name %>:</h2>
  <div class="card-buoy-container justify-content-between">
    <div class="row">
      <div class="card-buoy col-sm-12 col-md-12 col-lg-7 col-xl-7">
        <%= cl_image_tag @buoy.photo, height: 400, crop: :fill %>
          <% if @buoy.user == current_user %>
                <div id="owner-tag">
                    <i class="fas fa-crown"></i> Me
                </div>
              <% end %>
        <div class="card-buoy-description align-items-center">
          <h3><%= @buoy.name  %></h3>
          <div class="d-flex justify-content-around">
            <p><i class="fas fa-paperclip"></i><%= @buoy.category %></p>
            <p><i class="fas fa-ruler-combined"></i><%= @buoy.size  %></p>
            <p><i class="fas fa-tag"></i><%= @buoy.price %>€</p>
          </div>
          <p> <%= @buoy.description %> </p>
        </div>
      </div>

      <div class="card-buoy-map col-sm-12 col-md-12 col-lg-4 col-xl-4">
        <h2 class="caption p-3">Find this buoy:</h2>
        <div class="card-buoy-address">
          <p><%= @buoy.address %></p>
        </div>
        <div
          id="map"
          style="width: 100%;
          height: 45vh;"
          data-markers="<%= @marker.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        >
        </div>
        <div class="form-container-small d-flex justify-content-around">
          <%= simple_form_for [@buoy, @booking] do |f| %>
            <%= f.input :start_date, as: :string, label:false, required: true, placeholder:"Choose your dates here !", include_blank: false, input_html: { id: "range_start" } %>
            <%= f.submit "Book it!", class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="reviews">
    <% sum = 0 %>
    <% @reviews.each do |review| %>
      <% sum += review.rating %>
    <% end %>
    <% if @reviews.size != 0 %>
      <% avg = sum / @reviews.size %>
      <h2 class="caption p-3"> <%= @buoy.name %> is rated
      <% avg.round.times do  %>
        <span class="star-full"><%= "<i class='fas fa-star'></i>".html_safe %></span>
      <% end %>
      <% (5 - avg.round).times do  %>
       <span class="star-empty"> <%= "<i class='far fa-star'></i>".html_safe %></span>
      <% end %>
      <br></h2>
        <div class="card-buoy-map col-sm-12 col-md-12 col-lg-7 col-xl-7">
          <h2>What other users said:</h2>
          <% @reviews.each do |review| %>
            <p> <i>" <%= review.content %> "</i> </p>
            <p>  <% review.rating.round.times do  %>
              <span class="star-full"> <%= "<i class='fas fa-star'></i>".html_safe %> </span>
           <% end %>
      <% (5 - review.rating.round).times do  %>
       <span class="star-empty"> <%= "<i class='far fa-star'></i>".html_safe %></span>
      <% end %>  </p>
            <hr>
          <% end %>
        </div>
    <% else %>
      <h2 class="caption p-3"> <%= @buoy.name %> is not rated yet :( </h2>
      <div class="row">
        <div class="card-buoy-map col-sm-12 col-md-12 col-lg-7 col-xl-7">
          <p class="text-center font-italic pt-3">To become the first reviewer, book the buoy and tell us the whole story...</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('life-ring-regular.png') %>
    <title>Book a Buoy!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner">
  <h2>Bored at the pool ? Don't forget the most important tool!</h2>
  <h1>Book a Buoy ... </h1>
</div>

<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>
<h2>CARDS</h2>
<br>

app/views/reviews/new.html.erb
<div class="container">
  <div class="form-container-large">
    <h2 class="caption pt-3"> Had a good time? Let the world know!</h2>
      <p>Please take some time to review your booking of <%= @buoy.name %> </p>
<br>

      <%= simple_form_for [@booking, @review] do |f| %>
        <%= f.text_area :content, label: "Your review:", placeholder: "Did the buoy correspond to its description? Did you have a good experience with the renter? With the buoy?... ", style: "width:100%", rows: 10 %>
        <div class="stars p-2">
        <%= f.input :rating, collection: (1..5).to_a, label: "Your rating" %>
        </div>
          <br>
        <%= f.submit "Thank you for the review!", class: "btn btn-success" %>
      <% end %>
      <span class="btn btn-back btn-outline-primary"> <%= link_to "Back to <i class='far fa-life-ring'></i>".html_safe, bookings_path %> </span>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <%= link_to buoys_path , class: "navbar-brand" do %>
    <%= image_tag("logo.png", id: "navbar-logo") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to current_user.email, "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/myriamchah", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" >
            <%= link_to "<i class='far fa-life-ring'></i>&nbsp;&nbsp; See my dashboard".html_safe, bookings_path, class: "dropdown-item" %>

            <%= link_to "<i class='far fa-life-ring'></i>&nbsp;&nbsp; Manage my buoys".html_safe, mybuoys_path, class: "dropdown-item" %>

            <%= link_to "<i class='far fa-life-ring'></i>&nbsp;&nbsp; Add a buoy to rent".html_safe, new_buoy_path, class: "dropdown-item" %>

            <%= link_to "<i class='fas fa-life-ring'></i>&nbsp;&nbsp; Log out".html_safe, destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>